# Use a base image with Node.js installed
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json from the frontend directory
COPY package.json package-lock.json ./

# Install dependencies, including Mocha as a development dependency
RUN npm install --silent

# Install Mocha globally
RUN npm install --global mocha

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Expose port 3000 (or any other port your server is running on)
EXPOSE 3000

# Command to run the server and execute tests in the background
CMD ["sh", "-c", "npm start & npm run test_webDriver"]
