# Use a base image with Node.js installed
FROM node:alpine as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json from the frontend directory
COPY package.json package-lock.json ./

# Install dependencies, including Mocha as a development dependency
RUN npm install --silent

# Install Mocha globally
RUN npm install --global mocha

# Copy the rest of the application files
COPY . .

# Install node-polyfill-webpack-plugin to polyfill Node.js core modules
RUN npm install node-polyfill-webpack-plugin --save-dev

# Add a webpack.config.js file with resolve fallback for 'crypto' module
RUN echo "module.exports = { resolve: { fallback: { 'crypto': require.resolve('crypto-browserify') } } }" > webpack.config.js

# Build the application
RUN npm run build

# Use a lightweight Nginx image as the final image
FROM nginx:alpine

# Copy the built files from the previous stage to the NGINX directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Command to run the NGINX server
CMD ["nginx", "-g", "daemon off;"]
