name: Docker Build and Test

on:
  push:
    branches:
      - main
      - devlop
      - ci_test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ci-test .

    - name: Test Docker container
      run: docker run ci-test npm test
