name: Run WebDriver Tests with Chrome

on:
  push:
    branches:
      - main
      - develop
      - ci_test_new

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install --prefix frontend

    - name: Install WebDriver
      run: npm install selenium-webdriver

    - name: Build Docker container
      run: |
        cd frontend
        docker build -t katzir/ci-test .

  
            
    - name: Run Docker container and execute tests
      run: |
       cd frontend
       pwd
       docker run katzir/ci-test npm run test_webDriver
       
